name: transaction-systems-aggregator
services:
#=========================================================================
# SQL Server
# -----------------
# Server: localhost
# Username: sa
# Password: P@ssword1
#=========================================================================
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql
    environment:
      - MSSQL_SA_PASSWORD=P@ssw0rd1
      - MSSQL_PID=Evaluation
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

#=========================================================================
# Deploy the database scripts
#=========================================================================
  dbTransactionAggregator:
    image: erikbra/grate:latest
    entrypoint: ['']
    command: 
      - /bin/sh
      - -c
      - |
        retry_count=0
        max_retries=5
        while [ $retry_count -lt $max_retries ]
        do
          echo "Attempt $((retry_count + 1))..."
          ./grate --connstring="Server=sql;Database=dbTransactionAggregator;User Id=sa;Password=P@ssw0rd1;TrustServerCertificate=True" --sqlfilesdirectory=/db --version=1.0.0 --databasetype=sqlserver --silent --outputPath=/output --createdatabase=true --environment=LOCAL --transaction=false
          if [ $? -eq 0 ]; then
            echo "Command succeeded."
            exit 0
          fi
          retry_count=$((retry_count + 1))
          echo "Command failed. Retrying in 5 seconds..."
          sleep 5
        done
        echo "Command failed after $max_retries attempts."
        exit 1
    volumes:
      - ./dbTransactionAggregator:/db
    depends_on:
      - sql

  dbTransactionAggregatorArchive:
    image: erikbra/grate:latest
    entrypoint: ['']
    command: 
      - /bin/sh
      - -c
      - |
        retry_count=0
        max_retries=5
        while [ $retry_count -lt $max_retries ]
        do
          echo "Attempt $((retry_count + 1))..."
          ./grate --connstring="Server=sql;Database=dbTransactionAggregatorArchive;User Id=sa;Password=P@ssw0rd1;TrustServerCertificate=True" --sqlfilesdirectory=/db --version=1.0.0 --databasetype=sqlserver --silent --outputPath=/output --createdatabase=true --environment=LOCAL --transaction=false
          if [ $? -eq 0 ]; then
            echo "Command succeeded."
            exit 0
          fi
          retry_count=$((retry_count + 1))
          echo "Command failed. Retrying in 5 seconds..."
          sleep 5
        done
        echo "Command failed after $max_retries attempts."
        exit 1
    volumes:
      - ./dbTransactionAggregatorArchive:/db
    depends_on:
      - sql

#=========================================================================
# Kafka
# -----------------
#
# Control Center
# Server: http://localhost:9021
#=========================================================================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      retries: 10
      start_period: 10s
    command: >
      bash -c "
      /etc/confluent/docker/run &
      echo 'Waiting for Kafka to start...';
      sleep 10;
      wait
      "

  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.0
    container_name: schema-registry
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    ports:
      - "8081:8081"

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.4.0
    container_name: control-center
    depends_on:
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_started
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka:29092
      CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONTROL_CENTER_REPLICATION_FACTOR: 1
    ports:
      - "9021:9021"
